=== anhth2808/BT-Nhom-XML/data/QuanLyNhanVienSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    
    <xs:element name="QuanLyNhanVien">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="NhanVien" maxOccurs="unbounded" />
                <xs:element ref="PhongBan" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="ChucVu" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="HDLD"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Khoa -->
        <xs:key name="PKNhanVien">
            <xs:selector xpath="NhanVien/MaNV"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="PKPhongBan">
            <xs:selector xpath="PhongBan/MaPB"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="PKChucVu">
            <xs:selector xpath="ChucVu/MaCV"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="PKHDLD">
            <xs:selector xpath="HDLD/MaHDLD"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        
        <!-- Khoa phu-->
        <xs:keyref refer="PKPhongBan" name="PKNhanVientoPhongBan">
            <xs:selector xpath="NhanVien/MaPB"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
        <xs:keyref refer="PKChucVu" name="PKNhanVientoChucVu">
            <xs:selector xpath="NhanVien/MaCV"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
        <xs:keyref refer="PKHDLD" name="PKNhanVientoHDLD">
            <xs:selector xpath="NhanVien/MaHDLD"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
    </xs:element>
    
    
    <xs:element name="NhanVien">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MaNV">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="NV\d{4}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="TenNV" type="xs:string" />
                <xs:element name="DiaChi" type="xs:string" />
                <xs:element name="NgaySinh" type="xs:date" />
                <xs:element name="GioiTinh" type="xs:string" />
                <xs:element name="DanToc" type="xs:string" />
                <xs:element name="TonGiao" type="xs:string" />
                <xs:element name="CMND" type="xs:string" />
                <xs:element name="MaPB" type="xs:string" />
                <xs:element name="MaCV" type="xs:string" />
                <xs:element name="MaHDLD" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="PhongBan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MaPB">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="PB\d{4}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="TenPB" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ChucVu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MaCV">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="CV\d{4}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="TenCV" type="xs:string"/>
                <xs:element name="PhuCap" type="xs:double"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="HDLD">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MaHDLD">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="HDLD\d{4}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="NgayBatDau" type="xs:date"/>
                <xs:element name="NgayKetThuc" type="xs:date"/>
                <xs:element name="HeSoLuong" type="xs:double"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    
    
    

</xs:schema>

=== anhth2808/BT-Nhom-XML/data/QuanLyNhanVien-Instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuanLyNhanVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/Do-An-XML/data/QuanLyNhanVienSchema.xsd">
    <NhanVien>
        <MaNV>MaNV0</MaNV>
        <TenNV>TenNV0</TenNV>
        <DiaChi>DiaChi0</DiaChi>
        <NgaySinh>2006-05-04</NgaySinh>
        <GioiTinh>GioiTinh0</GioiTinh>
        <DanToc>DanToc0</DanToc>
        <TonGiao>TonGiao0</TonGiao>
        <CMND>CMND0</CMND>
        <MaPB>MaPB0</MaPB>
        <MaCV>MaCV0</MaCV>
        <MaHDLD>MaHDLD0</MaHDLD>
    </NhanVien>
    <NhanVien>
        <MaNV>MaNV1</MaNV>
        <TenNV>TenNV1</TenNV>
        <DiaChi>DiaChi1</DiaChi>
        <NgaySinh>2006-05-04</NgaySinh>
        <GioiTinh>GioiTinh1</GioiTinh>
        <DanToc>DanToc1</DanToc>
        <TonGiao>TonGiao1</TonGiao>
        <CMND>CMND1</CMND>
        <MaPB>MaPB1</MaPB>
        <MaCV>MaCV1</MaCV>
        <MaHDLD>MaHDLD1</MaHDLD>
    </NhanVien>
    <PhongBan>
        <MaPB>MaPB0</MaPB>
        <TenPB>DayLaPhongBan0</TenPB>
    </PhongBan>
    <PhongBan>
        <MaPB>MaPB1</MaPB>
        <TenPB>DayLaPhongBan1</TenPB>
    </PhongBan>
    <ChucVu>
        <MaCV>MaCV0</MaCV>
        <TenCV>DayLaChucvu-</TenCV>
        <PhuCap>0</PhuCap>
    </ChucVu>
    <ChucVu>
        <MaCV>MaCV1</MaCV>
        <TenCV>DayLaChucvu1</TenCV>
        <PhuCap>600000</PhuCap>
    </ChucVu>
    <HDLD>
        <MaHDLD>MaHDLD0</MaHDLD>
        <TenHDLD>Day la HDLD0</TenHDLD>
        <NgayBatDau>20010-05-04</NgayBatDau>
        <NgayKetThuc>20011-05-04</NgayKetThuc>
        <HeSoLuong>2.5</HeSoLuong>
    </HDLD>
    <HDLD>
        <MaHDLD>MaHDLD1</MaHDLD>
        <TenHDLD>Day la HDLD1</TenHDLD>
        <NgayBatDau>2006-05-04</NgayBatDau>
        <NgayKetThuc>20012-05-04</NgayKetThuc>
        <HeSoLuong>2.34</HeSoLuong>
    </HDLD>
</QuanLyNhanVien>

=== anhth2808/BT-Nhom-XML/data/QuanLyNhanVien-Instance3.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuanLyNhanVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/Do-An-XML/data/QuanLyNhanVienSchema.xsd">
    <NhanVien>
        <MaNV>MaNV0</MaNV>
        <TenNV>Trần Hoàng Anh</TenNV>
        <DiaChi>61/8, ĐTN, VP, Nha Trang, Khánh Hòa, Việt Nam, Trái Đất, Vũ trụ 7</DiaChi>
        <NgaySinh>1998-08-28</NgaySinh>
        <GioiTinh>Nam</GioiTinh>
        <DanToc>Kinh</DanToc>
        <TonGiao>Không</TonGiao>
        <CMND>123456789</CMND>
        <MaPB>MaPB0</MaPB>
        <MaCV>MaCV0</MaCV>
        <MaHDLD>MaHDLD0</MaHDLD>
    </NhanVien>
    <NhanVien>
        <MaNV>MaNV1</MaNV>
        <TenNV>Trần Hoàng Em</TenNV>
        <DiaChi>61/8, ĐTN, VP, Nha Trang, Khánh Hòa, Việt Nam, Trái Đất, Vũ trụ 1</DiaChi>
        <NgaySinh>1998-08-27</NgaySinh>
        <GioiTinh>Nam</GioiTinh>
        <DanToc>Kinh</DanToc>
        <TonGiao>Không</TonGiao>
        <CMND>987654321</CMND>
        <MaPB>MaPB1</MaPB>
        <MaCV>MaCV1</MaCV>
        <MaHDLD>MaHDLD1</MaHDLD>
    </NhanVien>
    <PhongBan>
        <MaPB>MaPB0</MaPB>
        <TenPB>Phòng kế toán</TenPB>
    </PhongBan>
    <PhongBan>
        <MaPB>MaPB1</MaPB>
        <TenPB>Phòng hành chính</TenPB>
    </PhongBan>
    <ChucVu>
        <MaCV>MaCV0</MaCV>
        <TenCV>Nhân viên</TenCV>
        <PhuCap>0</PhuCap>
    </ChucVu>
    <ChucVu>
        <MaCV>MaCV1</MaCV>
        <TenCV>Quản lý</TenCV>
        <PhuCap>600000</PhuCap>
    </ChucVu>
    <HDLD>
        <MaHDLD>MaHDLD0</MaHDLD>
        <NgayBatDau>20010-05-04</NgayBatDau>
        <NgayKetThuc>20011-05-04</NgayKetThuc>
        <HeSoLuong>2.5</HeSoLuong>
    </HDLD>
    <HDLD>
        <MaHDLD>MaHDLD1</MaHDLD>
        <NgayBatDau>2006-05-04</NgayBatDau>
        <NgayKetThuc>20012-05-04</NgayKetThuc>
        <HeSoLuong>2.34</HeSoLuong>
    </HDLD>
<NhanVien><MaNV>0.3614820247466728</MaNV><TenNV>Hoang Cha</TenNV><DiaChi>61/8 Đoàn Trần Nghiệp</DiaChi><NgaySinh>2019-04-25</NgaySinh><GioiTinh>Nam</GioiTinh><DanToc>Hoàng</DanToc><TonGiao>Phật</TonGiao><CMND>2223</CMND><MaPB>MaPB0</MaPB><MaCV>MaCV1</MaCV><MaHDLD>0.8360003236254396</MaHDLD></NhanVien><HDLD><MaHDLD>0.8360003236254396</MaHDLD><NgayBatDau>2018-08-06</NgayBatDau><NgayKetThuc>2019-09-16</NgayKetThuc><HeSoLuong>100</HeSoLuong></HDLD></QuanLyNhanVien>

=== anhth2808/BT-Nhom-XML/data/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuanLyNhanVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/Do-An-XML/data/QuanLyNhanVienSchema.xsd">
    <NhanVien>
        <MaNV>MaNV0</MaNV>
        <TenNV>TenNV0</TenNV>
        <DiaChi>DiaChi0</DiaChi>
        <NgaySinh>2006-05-04</NgaySinh>
        <GioiTinh>GioiTinh0</GioiTinh>
        <DanToc>DanToc0</DanToc>
        <TonGiao>TonGiao0</TonGiao>
        <CMND>CMND0</CMND>
        <MaPB>MaPB0</MaPB>
        <MaCV>MaCV0</MaCV>
        <MaHDLD>MaHDLD0</MaHDLD>
    </NhanVien>
    <NhanVien>
        <MaNV>MaNV1</MaNV>
        <TenNV>TenNV1</TenNV>
        <DiaChi>DiaChi1</DiaChi>
        <NgaySinh>2006-05-04</NgaySinh>
        <GioiTinh>GioiTinh1</GioiTinh>
        <DanToc>DanToc1</DanToc>
        <TonGiao>TonGiao1</TonGiao>
        <CMND>CMND1</CMND>
        <MaPB>MaPB1</MaPB>
        <MaCV>MaCV1</MaCV>
        <MaHDLD>MaHDLD1</MaHDLD>
    </NhanVien>
</QuanLyNhanVien>
